### PR TITLE
Add proxy support though tunnel-agent

### LINKED ISSUE #64: support proxies
download should call got module using tunnel agent when user is behind a corporate proxy

### PR DESCRIPTION
**Pull request by alfonso-presa**
Fixes #64

### CODE REVIEW

**Comment by alfonso-presa** [comment]
BTW, Tests are passing both in travis and in my environment, and I'm behind a proxy so I guess everything is working fine.

**Comment by shinnn** [comment]
Thanks, @alfonso-presa.

@kevva @sindresorhus Should this fix be in [got](https://github.com/sindresorhus/got) module?

**Comment by alfonso-presa** [comment]
Making some more tests I realized it was not working correctly with https urls. The fix is turning the code a little bit unclean, but as deciding what method of the agent should be used is done outside got, I don't see any other way of handling this. Any suggestions?

Thanks!

**Comment by kevva** [comment]
I'm going to make this a separate module instead that I'll include with `download`.

**Comment by alfonso-presa** [comment]
Ok. Let me know if you need someone to test behind a proxy.

**Comment by kevva** [comment]
Yup, will do :).

**Comment by vrtxf** [comment]
I can test this extensively as well

**Comment by ThomasCrvsr** [comment]
Hello,

Any news about this PR ? I'm working with projects using imagemin and because of this proxy issue, installation doesn't work well ^^'

**Comment by kevva** [comment]
@ThomasCrvsr, have you tried installing it recently?

**Comment by ThomasCrvsr** [comment]
I had this problem weeks ago, and one of my collegue just had this problem while installing it this week. Should it be possible to downgrade the version of `download` required by dependencies of imagemin, until this problem is fixed ? (I don't have a global vision so it may be silly)

**Comment by LeiZeng** [comment]
@all fixed from caw:
https://github.com/kevva/caw/pull/9

**Comment by marc-guenther** [comment]
New version of [tunnel-agent@0.4.2](https://www.npmjs.com/package/tunnel-agent) has just been released. This contains the mikeal/tunnel-agent#15 fix. :-)

This should make f2d1049 and 7df7422 obsolete.

**Comment by plrthink** [comment]
Any updates on this? I'm still getting error 'tunneling socket could not be established, cause=Parse Error'.

**Comment by shinnn** [comment]
@plrthink Good contribution is always welcome.

**Pull request closed without merging**
