### PR TITLE
Set utimes from original files

### PR DESCRIPTION
**Pull request by piranna**
This fixes issue #78

### CODE REVIEW

**Comment by shinnn** [comment]
Only`vinyl` and `vinyl-fs` updates are meaningful and all the other chnages are not needed. https://nodesource.com/blog/semver-tilde-and-caret

**Comment by shinnn** [comment]
And squash the commits into a single commit.

**Comment by piranna** [comment]
Done, commits cleaned and squashed.

**Comment by shinnn** [comment]
Thanks. We'll publish a new version soon.

**Comment by shinnn** [comment]
https://github.com/kevva/download/commit/cbe4c6cba19a600bffb0ac010db1df78263cdb05

**Comment by piranna** [comment]
Thank you :-)

**Pull request merged**
