### PR TITLE
Detect file extension if there's none

### PR DESCRIPTION
**Pull request by dkakashi69**
I download an audio file and it doesn't have a .mp3 file extesion so i made a little change.

### CODE REVIEW

**Comment by kevva** [comment]
@sindresorhus @silverwind, does this sound good to you?

@dkakashi69, this also needs tests.

**Comment by sindresorhus** [comment]
Looks fine.

**Comment by silverwind** [comment]
Could also expand this by using https://github.com/jshttp/mime-types to look up the preferred extension for the mime type when the magic byte check fails.

**Comment by kevva** [comment]
Yup, can use the same code as in https://github.com/sindresorhus/electron-dl/pull/20.

**Pull request merged**
