### PR TITLE
add rename

### PR DESCRIPTION
**Pull request by alex-zhang**
we need to rename the output filename.

### CODE REVIEW

**Comment by stevemao** [comment]
It was added before: https://github.com/kevva/download/commit/a36b04e6a9ff5cca2d52438f5e06853497dd1f37

Is this PR still relevant?

**Comment by stevemao** [comment]
Looks like the module has been rewritten so renaming is probably still relevant. I'd use `destination` for this though. If `destination` looks like a filename (based on the ext name maybe), rename to that.

**Comment by sindresorhus** [comment]
Ping @kevva

**Comment by dariocavada** [comment]
need also to rename the file output.
For solving fast the rename, I've changed the code as following:

`//const dest = output ? path.join(output, filenamify(path.basename(uri))) : null;
	const dest = output;
`
but would be good to have an option to do this or auto discover if output indicates a file or a folder.

**Comment by sindresorhus** [comment]
I think the option name should be `filename`. `rename` makes it sound like it accepts a function where you can rename the filename. This will also need a test and documentation updates.

**Comment by dajbd** [comment]
I also need to rename the output filename.
thank you.

**Comment by sindresorhus** [comment]
Closing this for lack of activity. Opened an issue for it: https://github.com/kevva/download/issues/124 PR welcome.

**Pull request closed without merging**
