### PR TITLE
Fix #105 - doesn't read all the bytes.

### LINKED ISSUE #105: Only downloads first chunks
When downloading a file that's larger than the fixture I use in tests, the following promise never resolves https://github.com/kevva/download/blob/master/index.js#L14-L21. To me, the code looks alright, and kinda identical to what it looks in `got`.

@floatdrop, any ideas?

### PR DESCRIPTION
**Pull request by jamestalmage**
See commit messages.

### CODE REVIEW

**Comment by jamestalmage** [comment]
this fixed the reproduction I created (I accidentally included it in the first two commits, deleted in the third). Not sure how to test.

**Comment by jamestalmage** [comment]
test added.

**Comment by floatdrop** [comment]
@jamestalmage I wonder if this can be fixed in `got` also.

**Comment by jamestalmage** [comment]
I don't think it was a `got` issue.

It was using the `response` event to try an capture the response stream. But the `got.stream` result already **is** the response stream.

**Comment by jamestalmage** [comment]
Well.
Bad news is the test I just added works on `master`. So...

**Comment by jamestalmage** [comment]
I'm going to bed, and have a full day tomorrow. I can try and write a better test in a day or two. Someone else can run with what I have here if they want.

**Comment by kevva** [comment]
I ran this with a test I had locally that failed in `master` and it passed with your code. I'm going to merge :). Thank you very much!

**Pull request closed without merging**
