### PR TITLE
Add missing available option in the readme

### PR DESCRIPTION
**Pull request by simonepri**
See https://github.com/kevva/decompress options

### CODE REVIEW

**Comment by silverwind** [comment]
Maybe it's better to just link to decompress's README instead, to avoid duplication.

**Comment by simonepri** [comment]
Decompress options could change over time. Since this package installs a particular version of it, I think that  duplication can make sense. However a link to the decompress's readme it could be added also. What do you think abou it?

**Comment by simonepri** [comment]
There are other missing available options, like plugins.
A link to the decompress readme is a must.

**Comment by simonepri** [comment]
@silverwind  See #135

**Pull request closed without merging**
